### ISSUE TITLE
Failed to Launch on Ubuntu 22.04 with Python3

### ISSUE THREAD

**Issue by brandenk514** [scottpeterman/UglyPTY#1]
```shell
root@vm:/opt/uglypty# source bin/activate
(uglypty) root@vm/opt/uglypty# python3 -m uglypty
Key saved to "crypto.key".
settings.sqlite created
Created base plugin catalog.yaml
['/opt/uglypty/lib/python3.11/site-packages/uglypty/__main__.py']
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, vnc, linuxfb, minimalegl, offscreen, vkkhrdisplay, minimal, eglfs, wayland, xcb.

Aborted (core dumped)
``` 
Let me know what additional logs you need!

**Comment by scottpeterman** [comment]
Can you verify if you have the libxcb dependencies installed? sudo apt install libxcb-render0 libxcb-shape0 libxcb-xfixes0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxcb-render0 is already the newest version (1.14-3ubuntu3).
libxcb-render0 set to manually installed.
libxcb-shape0 is already the newest version (1.14-3ubuntu3).
libxcb-shape0 set to manually installed.
libxcb-xfixes0 is already the newest version (1.14-3ubuntu3).
libxcb-xfixes0 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 78 not upgraded.
 
I haven't verified every utility, but the base app should run. Here it is running on Ubuntu 22.04 in vmware player 17: 
![image](https://github.com/scottpeterman/UglyPTY/assets/30607644/ff1bed28-6aba-41c6-8d03-7aff4d29d1e8)

**Comment by scottpeterman** [comment]
Try adding the libxcb dependencies: sudo apt install libxcb-render0 libxcb-shape0 libxcb-xfixes0
Here it is running on Ubuntu 22.04 in VMWare player 17: 
![image](https://github.com/scottpeterman/UglyPTY/assets/30607644/62321f9a-274d-4911-88ea-a235128aa4a6)

**Comment by brandenk514** [comment]
I got it up! Those packages were installed already, but I add this and it brought it up.

`apt install -y libxcb-cursor0`

**Comment by scottpeterman** [comment]
cool, thanks for letting me know, I'll add to the readme
